dbtgen:
  outputs:
    dev:
      dataset: dbt_sonny
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      priority: interactive
      method: service-account
      keyfile: "{{ env_var('GCP_KEYFILE') }}"
      project: "{{ env_var('GCP_PROJECT') }}"
      threads: 4
      type: bigquery
  target: dev
